language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "tQotlWFt2nwysJyA8yTobg0qegO6tRDh7Unyxpifb7KNEIf+usj6ip9bJV5p2wJGQtRZj5ZI7oTZmJUNP8TSoZ22o0H4mPE8aGk7Sv0R3Xwkf+xWBYnt0X4VDP2WIZTauXTmCcDSYnsIbwU+HKvvmf/eFK+UR4qAlwnn4gv2EeZ/M6bfbV4ilHDREZSzcFbtSJN0LIYBj2dqm2j2UkmEEtt77PrUq+1e1NfSqYq0vbP5zddgwFDHDdrahlSTqpi6quUbGdlNSPJVm0gtIG+w4vSBo68iAxSYWBfi1P8l7GLPfxDyWEdvseKZOn9OuO4hnVGM4Kxmh25QF1uGUXpnDYCEUIY9pn0gO5bsILQg2y4HDEasCB+hd2QF0cSiDoGpfmMRZ+3wXc2QC8Qn1ohZqdJA/PvgVPSbOppk8L7fyP+QUmxXqwQOKB6OlprO263YQ3YMpcomdgXIb6q6ZYeK6NvL/JmyITaAtiEnyPEfoDc6xj0JNpp2033vZzReXTcDSgx5+yn6kgnODK0Sw8Ey1azkx2mxw1NwsnzqkCi1sjY+CNrO6sPA+PkDAMchZAzliurf+wzuG3J4GjxefkXVupla3joK68xDi0RF0nOe1pxP91sWezS3dTeAu1N56IkHoHyj2ESpAbp++EqR8HuqQ1pc0nIsbt2eckqZ6KqK6f8="
